name 'file_handler'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures file_handler'
long_description 'Installs/Configures file_handler'
version '0.1.0'
